// web/src/components/Dropdown.vue
<template lang='pug'>
button.dropdown.outline-parent(
  v-on-clickaway='hide'
  @keydown.esc='hide'
  @keydown.prevent.down='focusNext'
  @keydown.prevent.up='focusPrevious'
  @keydown.enter='enter'
  @keydown.space='enter'
  :data-visible='visible'
)
  //- @blur='hide()'
  //- @focus='show()'
  .textbox.outline-child(tabindex='-1' @mousedown='toggle()')
    .text {{ options[selectedIndex].text }}
    ChevronDownIcon.chevron(size='18')
  .box(v-show='visible')
    template(v-for='(option, index) in options')
      .separator(v-if='option.type === "separator"')
      .text(v-else-if='option.type === "text"') {{ option.text }}
      .space(v-else-if='option.type === "space"')
      .button(
        v-else-if='option.type === "button"'
        :class='{highlight: index === focusedIndex}'
        @mouseover='focusedIndex = index'
        @mousedown='focusedIndex = index'
        @mouseout='focusedIndex = null'
        @click='hide(); option.handler()'
      ) {{ option.text }}
      .option(
        v-else
        :class='{highlight: index === focusedIndex}'
        @mouseover='focusedIndex = index'
        @mousedown='focusedIndex = index'
        @mouseout='focusedIndex = null'
        @click='select(index)'
      ) {{ option.text }}
</template>

<script>
import { mixin as clickaway } from 'vue-clickaway'
import { ChevronDownIcon } from 'vue-feather-icons'

export default {
  mixins: [clickaway],
  components: {
    ChevronDownIcon,
  },
  data: function () {
    return {
      visible: false,
      focusedIndex: null, // initialized by open()
    }
  },
  props: {
    options: Array,
    value: String,
  },
  computed: {
    selectedIndex () {
      // get the index of the value
      const x = this.options.findIndex(option => option.id === this.value)
      return x
    },
  },
  methods: {
    toggle () {
      this.visible = !this.visible
      this.focusedIndex = this.selectedIndex
    },
    hide () {
      this.visible = false
    },
    show () {
      this.visible = true
      this.focusedIndex = this.selectedIndex
    },
    select (index) {
      if (this.selectedIndex !== index) {
        this.$emit('input', this.options[index].id)
      }
      this.hide()
    },
    selectHighlighted () {
      const highlightedOption = this.options[this.focusedIndex]
      if (highlightedOption.type === 'button') {
        highlightedOption.handler()
      } else {
        this.$emit('input', this.options[this.focusedIndex].id)
      }
      this.hide()
    },
    enter () {
      if (this.visible) this.selectHighlighted()
      else this.show()
    },
    // direction: 1 or -1
    moveFocus (direction) {
      let index = this.focusedIndex

      // start from top/bottom if nothing is focused
      if (index === null && direction === 1) index = -1
      if (index === null && direction === -1) index = this.options.length

      while (true) {
        const nextIndex = index + direction
        const nextOption = this.options[nextIndex]
        if (!nextOption) break
        else if (!nextOption.type || nextOption.type === 'button') {
          this.focusedIndex = nextIndex
          break
        }
        index = nextIndex
      }
    },
    focusNext () {
      this.moveFocus(1)
    },
    focusPrevious () {
      this.moveFocus(-1)
    },
  },
}
</script>

<style lang='sass' scoped>
button.dropdown
  background-color: transparent
  border: none
  font-family: inherit
  font-weight: inherit
  font-size: inherit
  text-align: left
  color: inherit
  width: 200px
  position: relative
  outline: none
  $border-width-increase: 1px
  &[data-visible="true"]
    .textbox
      // border-color: var(--line-highlight-color)
      // box-shadow: 0px 0px 0px $border-width-increase var(--line-highlight-color)
  &:not([data-visible="true"])
    .textbox:hover
      // border-color: var(--line-color)
      box-shadow: 0px 0px 0px 1px var(--line-color)
  .textbox
    display: flex
    align-items: center
    width: auto
    cursor: pointer
    padding: 8px 0px
    height: 36px
    box-sizing: border-box
    transition: all 0.15s
    border-radius: 3px
    box-shadow: 0px 0px 0px 1px transparent
    // border-width: 1px
    // border-style: solid
    // border-color: transparent
    .text
      overflow: hidden
      text-overflow: ellipsis
      margin-left: 16px
    .chevron
      margin-left: 2px
      margin-right: 10px
      margin-top: 2px
  .box
    position: absolute
    font-weight: 600
    padding: 0px 0px
    background-color: var(--dropdown-background-color)
    box-shadow: var(--highlight-shadow)
    border-radius: 3px
    min-width: 100%
    margin-top: $border-width-increase
    border: 1px solid var(--line-color)
    font-size: 14px
    .space
      height: 8px
    .text
      padding: 6px 16px
      font-size: 12px
      opacity: 0.5
    .separator
      width: 100%
      height: 1px
      margin: 8px 0px
      background-color: var(--light-line-color)
    .button
      padding: 8px 16px
      cursor: pointer
      color: var(--button-color)
      font-weight: 700
      &.highlight
        background-color: var(--button-color)
        color: var(--button-text-color)
    .option
      padding: 8px 16px
      cursor: pointer
      &.highlight
        background-color: var(--button-color)
        color: var(--button-text-color)

.outline-parent:focus, .outline-parent > .outline-child:focus
    outline: none
.outline-parent:focus > .outline-child, .outline-parent[data-visible='true'] > .outline-child
    box-shadow: 0px 0px 0px 2px var(--line-highlight-color)
</style>

// src/lib/Dropdown.svelte
<script lang="ts">
  import { checkShortcut } from './general'

  export let value: string
  let text = value
  export let options: string[]
  let dragSwitching = false
  export let menuMaxHeight = 140
  function filterOptions(options: string[], text: string) {
    let filtered = []
    const lcText = text.toLowerCase()
    for (const option of options) {
      let lcOption = option.toLowerCase()
      if (lcOption.startsWith(lcText)) {
        filtered.push(option)
      }
    }
    return filtered
  }
  $: filteredOptions = filterOptions(options, text)
  $: if (text.length > 0 && filteredOptions.length > 0) {
    selected = filteredOptions[0]
  }
  let visible = false
  let focused = false
  let selected = ''
  function onInput(e: any) {
    if (focused && !visible) {
      if (e.inputType === 'insertText' && e?.data) {
        open()
        text = e.data
      } else {
        e.preventDefault()
      }
    }
  }

  let inputEl: HTMLInputElement
  function open() {
    visible = true
    focused = true
    text = ''
    selected = value
    inputEl.focus()
  }
  function close() {
    visible = false
    text = value
  }
  function focus() {
    focused = true
  }
  function defocus() {
    focused = false
    close()
  }
  function fieldMouseDown() {
    if (visible) {
      close()
    } else {
      open()
      dragSwitching = true
    }
  }
  function itemMouseUp(newValue: any) {
    if (dragSwitching) pick(newValue)
  }
  function pick(newValue: any) {
    value = newValue
    text = newValue
    close()
  }
  let menuEl: HTMLDivElement
  function scrollTo(index: number) {
    let itemEl = menuEl.querySelector(`div:nth-child(${index + 1})`)
    if (itemEl) {
      let menuRect = menuEl.getBoundingClientRect()
      let itemRect = itemEl.getBoundingClientRect()
      if (menuRect.bottom < itemRect.bottom) {
        menuEl.scrollTop += itemRect.bottom - menuRect.bottom
      } else if (menuRect.top > itemRect.top) {
        menuEl.scrollTop -= menuRect.top - itemRect.top
      }
    }
  }
  function keydown(e: KeyboardEvent) {
    if (checkShortcut(e, 'ArrowUp')) {
      let i = filteredOptions.findIndex((o) => o === selected)
      if (i >= 1) {
        selected = filteredOptions[i - 1]
        scrollTo(i - 1)
      }
      if (!visible) open()
    } else if (checkShortcut(e, 'ArrowDown')) {
      let i = filteredOptions.findIndex((o) => o === selected)
      if (i < filteredOptions.length - 1) {
        selected = filteredOptions[i + 1]
        scrollTo(i + 1)
      }
      if (!visible) open()
    } else if (checkShortcut(e, 'Enter')) {
      if (selected !== '') {
        pick(selected)
      }
    } else if (checkShortcut(e, ' ')) {
      if (visible && text === '') {
        pick(selected)
      } else if (!visible) {
        open()
      }
    } else {
      return
    }
    e.preventDefault()
    let el = e.target as HTMLElement
    let menu = el.parentElement
    if (menu) {
      menu.scrollTo({ left: 0, top: el.clientTop + el.clientHeight })
    }
  }
</script>

<svelte:window on:mouseup={() => (dragSwitching = false)} />
<div class="dropdown" class:focused on:keydown={keydown}>
  <div class="field" on:mousedown|preventDefault={fieldMouseDown}>
    <input
      bind:this={inputEl}
      bind:value={text}
      on:focus={focus}
      on:blur={defocus}
      placeholder={value}
      class:hide-cursor={focused && !visible}
      on:beforeinput={onInput} />
    <div class="icon">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
        ><path d="M5 3l3.057-3 11.943 12-11.943 12-3.057-3 9-9z" /></svg>
    </div>
  </div>
  <div
    class="menu"
    class:visible
    bind:this={menuEl}
    on:mouseout={() => (selected = '')}
    on:blur={() => {}}
    style="max-height: {menuMaxHeight}px">
    {#each filteredOptions as option}
      <div
        class="item"
        on:mousedown|preventDefault
        on:mouseup={() => itemMouseUp(option)}
        on:click={() => pick(option)}
        on:mouseover={() => (selected = option)}
        on:focus={() => {}}
        class:selected={option === selected}
        class:current={option === value}>{option}</div>
    {/each}
    {#if filteredOptions.length === 0}
      <div class="item no-options">No options</div>
    {/if}
  </div>
</div>

<style lang="sass">
  .dropdown
    position: relative
    width: var(--dropdown-width, 100%)
  input, .item
    font-size: 12px
    padding: 4px 8px
  .field
    display: flex
    align-items: center
    margin: 0px
    background-color: #ffffff
    border: 1px solid #c6cddd
    border-radius: 3px
    transition: all 80ms var(--ease)
    &:active .icon
      transform: translateY(1px)
    :active .icon
      // For some weird reason on macOS 10.15.7, if you trigger the transition,
      // defocus the dropdown and switch to a diferent window, the transition
      // will stop working. This line fixes that (don't ask me why)
      transform: translateY(1px)
    .icon
      transition: transform 120ms var(--ease)
      display: flex
      padding: 4px
      padding-right: 6px
      svg
        width: 10px
        height: 10px
        opacity: 0.8
        background: #e7e9f4
        padding: 3px
        border-radius: 4px
        transform: rotate(90deg)
  .focused .field
    border-color: #0269f7
    box-shadow: 0px 0px 0px 2px rgba(#0269f7, 0.4)
  input
    min-width: 10px
    width: 100%
    outline: none
    border: none
    user-select: text
    -webkit-user-select: text
    background-color: transparent
    cursor: default
    margin: 0px
    &.hide-cursor
      color: transparent
      text-shadow: 0 0 0 #000000
      user-select: none
      -webkit-user-select: none
  .menu
    display: none
    position: absolute
    margin-top: 1px
    width: 100%
    background-color: #ffffff
    border: 1px solid #c6cddd
    box-sizing: border-box
    border-top: none
    border-radius: 3px
    overflow: auto
    box-shadow: 0px 2px 6px rgba(0, 0, 0, 0.2)
    z-index: 10
    &.visible
      display: block
  .item
    padding: 4px 6px
    &.selected
      background-color: #3C63ED
      color: #ffffff
    &.no-options
      color: #a6a6a6
      text-align: center
</style>
